[package]
name = "psykan-storage"
authors.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
sea-orm = { workspace = true }
tokio = { workspace = true }
