[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Bruno Bento"]
license = "MIT"
edition = "2024"
version = "0.1.0"
repository = "https://github.com/bocanada/psykan"

[workspace.dependencies]
pyo3 = "0.25.0"
